update readme and remove unused env variables
Othentic-Labs/PRNG-avs-example pull request #4
Opened 2024-12-20 07:57 UTC by himanshugarg06

2025-01-07 08:24 UTC, 0xpanicError requested changes
task trigger mechanism in `Execution_Service/index.js` can be moved to `Execution_Service/src/taskController.service.js`

2025-01-07 08:25 UTC, 0xpanicError reviewed
`leaderElection.js` -> `leaderElection.service.js`

2025-01-08 10:08 UTC, 0xpanicError approved these changes

2025-01-13 07:41 UTC, 0xtechdean commented on .env.example
> +OTHENTIC_REGISTRY_ADDRESS=0x41994741eD86Ec48e9578d0f64839E3F546466Fa
you can delete the `OTHENTIC_REGISTRY_ADDRESS` var

2025-01-13 07:43 UTC, 0xtechdean commented on Execution_Service/src/leaderElection.service.js
> +  const rpcUrl = process.env.L2_RPC;
those can be init once when the service starts. not need to re-init them again every time someone calls the  `electedLeader` function.

2025-01-15 15:24 UTC, 0xtechdean approved these changes

2025-01-16 05:21 UTC, merged